name = "ReplTree"
uuid = "d572e37e-0ce6-4d6f-8bb6-5ae049631b7f"
authors = ["Ashley Trowell"]
version = "0.1.0"

[deps]

[compat]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
